name: Documentation

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

env:
  PROTOC_VERSION: 25.1

concurrency:
  group: documentation
  cancel-in-progress: true

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
      - name: Install protoc
        run: |
          curl -LO "https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip"
          unzip "protoc-${PROTOC_VERSION}-linux-x86_64.zip" -d $HOME/.local

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Configure cache
        uses: Swatinem/rust-cache@v2

      - name: Setup pages
        uses: actions/configure-pages@v4

      - name: Build the documentation
        run: |
          cargo clean --doc
          cargo doc --no-deps

      - name: Add a redirect meta tag
        run: echo '<meta http-equiv="refresh" content="0;url=hatchet_sdk/index.html">' > target/doc/index.html

      - name: Remove the lock file
        run: rm target/doc/.lock

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/doc

  publish:
    name: Publish documentation
    environment:
      name: Documentation
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
